version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MYSQLHOST=mysql
      - MYSQLPORT=3306
      - MYSQLUSER=root
      - MYSQLPASSWORD=sykellpassword
      - MYSQLDATABASE=sykell
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sykellpassword
      MYSQL_DATABASE: sykell
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
